baseURL = "https://plagues.buffett.northwestern.edu"
languageCode = "en-us"
title = "Living With Plagues"
subtitle = "New Narratives for a World in Distress"
[related]
threshold = 20.0
includeNewer = false
toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 100.0

  [[related.indices]]
  name = "date"
  weight = 10.0

DefaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "Living With Plagues: New Narratives for a World in Distress"
    weight = 1
  [languages.fr]
    title = "Living With Plagues: New Narratives for a World in Distress"
    weight = 2