baseURL = "/"
languageCode = "en-us"
title = "Living With Plagues: New Narratives for a World in Distress"
[related]
threshold = 20.0
includeNewer = false
toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 100.0

  [[related.indices]]
  name = "date"
  weight = 10.0